### ISSUE TITLE
The code is dvrk_teleop/scripts is deprecated?

### ISSUE THREAD

**Issue by adnanmunawar** [jhu-dvrk/dvrk-ros#14]
Does this code serve any purpose here now? Doesn't the dvrk_kinematic package handle all this stuff.

**Comment by zchen24** [comment]
Yes. Since these scripts are deprecated, I am considering deleting them, What do you think?

**Comment by adnanmunawar** [comment]
Oh I figured that out later after I saw the Readme file. I think that is very useful code, even so its deprecated. Deleting it wouldn't be the best thing to do. Lets keep it, maybe we rename the folder to deprecated or something.
