### ISSUE TITLE
Possible Issue in Syntax while defining rotation matricies

### ISSUE THREAD

**Issue by adnanmunawar** [jhu-dvrk/dvrk-ros#15]
In the file psm_logic.cpp line 154:
frame6to7 means frame 7 defined in frame 6, right?

Using the same convention:
In the file mtsTeleop.cpp line 60 and 65:

Does mtm2psm mean PSMs frame 0 defined in MTMs frame 0?

And does psm6tomtm7 mean MTMs frame 7 defined in PSMs frame 6?

Assuming so, the formulas in line 83 and 95 do not make sense.

**Comment by adeguet1** [comment]
I believe this code has been deprecated.
