### ISSUE TITLE
Running dvrk_console_json in compatibility mode v1_4_0 causes termination with segfault

### ISSUE THREAD

**Issue by adnanmunawar** [jhu-dvrk/dvrk-ros#24]

**Comment by adeguet1** [comment]
I might have encountered this issue last week on the devel branch but I didn't have time to debug.   Can you try without the -p option to set the ROS period?   It seemed to make a difference for me.  If that prevents the crash, as a work-around, you can hard code the period you want in dvrk_console_json.cpp.

**Comment by adnanmunawar** [comment]
The problem went away by itself, I didn't even get to testing with the -p option. This is weird. I ll see if I can reproduce the problem

**Comment by adeguet1** [comment]
@adnanmunawar, should this be closed?   I didn't encounter this issue since it was first reported nor did the users at JHU.

**Comment by adeguet1** [comment]
@adnanmunawar, indeed, we had no recent report re. this issue.
