### ISSUE TITLE
Applications dialog boxes trigger on Value Edits rather than the RETURN Button

### ISSUE THREAD

**Issue by adnanmunawar** [jhu-dvrk/dvrk-ros#30]
When controlling the dVRK Manipulators using the QT GUI (mostly for debugging purposes), the control dialog boxes aren't the most convenient. They callback the underlying joint control function as soon as the user changes the value in the dialog box rather than waiting for the user to press ENTER.

**Comment by adeguet1** [comment]
Could you specify which dialog box you're referring to?  IO/PID/Arm/Console?

**Comment by adnanmunawar** [comment]
I am specifically talking about the PID console tab (Position Targets, P, I and D gains which are editable fields) but it might apply to other consoles tabs as well.

**Comment by adeguet1** [comment]
Can you pull the latest devel for cisst and sawRobotIO to test my changes:
  * https://github.com/jhu-cisst/cisst/commit/443c71275c0cbeec56a3bc707f5f62288e22daf3
  * https://github.com/jhu-saw/sawRobotIO1394/commit/12fa102ab990bcaaf85347fe471af613012a9edd

If this works for you, I'll also patch the "scale" for teleop in sawIntuitiveResearchKit.

**Comment by adnanmunawar** [comment]
Tested. This works as intended. Thanks
