### ISSUE TITLE
ERR when roslaunch dvrk_model ecm.launch  

### ISSUE THREAD

**Issue by MoonUniverse** [jhu-dvrk/dvrk-ros#34]
roslaunch dvrk_model ecm.launch 

PARAMETERS
 * /dvrk_ecm/rate: 100
 * /dvrk_ecm/robot_description: <?xml version="1....
 * /dvrk_ecm/source_list: ['joint_states_ro...
 * /dvrk_ecm/use_gui: True
 * /rate: 100
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /dvrk_ecm/
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [12089]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ece03df6-5e04-11ea-942c-08719092773c
process[rosout-1]: started with pid [12126]
started core service [/rosout]
process[dvrk_ecm/joint_state_publisher-2]: started with pid [12149]
process[dvrk_ecm/robot_state_publisher-3]: started with pid [12154]
process[rviz-4]: started with pid [12155]
[ERROR] [1583318584.240642619]: No link elements found in urdf file
[dvrk_ecm/robot_state_publisher-3] process has died [pid 12154, exit code 255, cmd /opt/ros/kinetic/lib/robot_state_publisher/state_publisher __name:=robot_state_publisher __log:=/home/ygx/.ros/log/ece03df6-5e04-11ea-942c-08719092773c/dvrk_ecm-robot_state_publisher-3.log].
log file: /home/ygx/.ros/log/ece03df6-5e04-11ea-942c-08719092773c/dvrk_ecm-robot_state_publisher-3*.log
[WARN] [1583318584.481518]: The 'use_gui' parameter was specified, which is deprecated.  We'll attempt to find and run the GUI, but if this fails you should install the 'joint_state_publisher_gui' package instead and run that.  This backwards compatibility option will be removed in Noetic.
^C[rviz-4] killing on exit
[dvrk_ecm/joint_state_publisher-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit

**Comment by adeguet1** [comment]
This launch file has not been maintained for a while will be deprecated in release 1.8 (already removed from the "devel" branch).   Instead, you should use `roslaunch dvrk_robot dvrk_arm_rviz_only.launch arm:=ECM`.   See https://github.com/jhu-dvrk/dvrk-ros/tree/master/dvrk_robot/launch
