### ISSUE TITLE
libDeckLinkAPI.so: cannot open shared object file: No such file or directory [FATAL] [1583319206.210301791]: Failed to PAUSE stream, check your gstreamer configuration

### ISSUE THREAD

**Issue by MoonUniverse** [jhu-dvrk/dvrk-ros#35]
roslaunch dvrk_robot gscam_decklink_stereo.launch rig_name:=jhu_daVinci

SUMMARY
========

PARAMETERS
 * /jhu_daVinci/left/decklink/jhu_daVinci_left/camera_info_url: package://gscam/e...
 * /jhu_daVinci/left/decklink/jhu_daVinci_left/camera_name: jhu_daVinci_left
 * /jhu_daVinci/left/decklink/jhu_daVinci_left/frame_id: /decklink_frame
 * /jhu_daVinci/left/decklink/jhu_daVinci_left/gscam_config: decklinkvideosrc ...
 * /jhu_daVinci/left/decklink/jhu_daVinci_left/sync_sink: False
 * /jhu_daVinci/right/decklink/jhu_daVinci_right/camera_info_url: package://gscam/e...
 * /jhu_daVinci/right/decklink/jhu_daVinci_right/camera_name: jhu_daVinci_right
 * /jhu_daVinci/right/decklink/jhu_daVinci_right/frame_id: /decklink_frame
 * /jhu_daVinci/right/decklink/jhu_daVinci_right/gscam_config: decklinkvideosrc ...
 * /jhu_daVinci/right/decklink/jhu_daVinci_right/sync_sink: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /jhu_daVinci/right/
    decklink_transform (tf/static_transform_publisher)
  /jhu_daVinci/left/decklink/
    jhu_daVinci_left (gscam/gscam)
  /jhu_daVinci/left/
    decklink_transform (tf/static_transform_publisher)
  /jhu_daVinci/right/decklink/
    jhu_daVinci_right (gscam/gscam)

auto-starting new master
process[master]: started with pid [15885]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5fa95f24-5e06-11ea-942c-08719092773c
process[rosout-1]: started with pid [15898]
started core service [/rosout]
process[jhu_daVinci/left/decklink/jhu_daVinci_left-2]: started with pid [15915]
process[jhu_daVinci/left/decklink_transform-3]: started with pid [15916]
process[jhu_daVinci/right/decklink/jhu_daVinci_right-4]: started with pid [15919]
process[jhu_daVinci/right/decklink_transform-5]: started with pid [15937]
[ INFO] [1583319206.079828523]: Using gstreamer config from rosparam: "decklinkvideosrc connection=sdi device-number=1 ! videoconvert"
[ INFO] [1583319206.082945732]: camera calibration URL: package://gscam/examples/uncalibrated_parameters.ini
[ WARN] [1583319206.083128904]: [jhu_daVinci_left] does not match name default in file /home/ygx/RBE501_dVRK_Project/catkin_ws_modified/src/gscam/examples/uncalibrated_parameters.ini
[ INFO] [1583319206.083148611]: Loaded camera calibration from package://gscam/examples/uncalibrated_parameters.ini
[ INFO] [1583319206.090723689]: Using gstreamer config from rosparam: "decklinkvideosrc connection=sdi device-number=0 ! videoconvert"
[ INFO] [1583319206.093904010]: camera calibration URL: package://gscam/examples/uncalibrated_parameters.ini
[ WARN] [1583319206.094061362]: [jhu_daVinci_right] does not match name default in file /home/ygx/RBE501_dVRK_Project/catkin_ws_modified/src/gscam/examples/uncalibrated_parameters.ini
[ INFO] [1583319206.094079712]: Loaded camera calibration from package://gscam/examples/uncalibrated_parameters.ini
[ INFO] [1583319206.210134409]: Time offset: 1583292071.615
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
[FATAL] [1583319206.210301791]: Failed to PAUSE stream, check your gstreamer configuration.
[FATAL] [1583319206.210314451]: Failed to initialize gscam stream!
[ INFO] [1583319206.213197303]: Time offset: 1583292071.615
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
[FATAL] [1583319206.213345622]: Failed to PAUSE stream, check your gstreamer configuration.
[FATAL] [1583319206.213361053]: Failed to initialize gscam stream!
[jhu_daVinci/left/decklink/jhu_daVinci_left-2] process has finished cleanly

**Comment by adeguet1** [comment]
That looks like a problem with the DeckLink drivers: `libDeckLinkAPI.so: cannot open shared object file: No such file or directory`.  Did you read: https://github.com/jhu-dvrk/dvrk-ros/blob/master/dvrk_robot/video.md#blackmagic-decklink-duo-frame-grabber
